/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.UserRole;

import Business.Employee.FosterParent;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bhash
 */
public class Adoption extends javax.swing.JPanel {

    /**
     * Creates new form Donation
     */
      private JPanel panelRight;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    public Adoption(JPanel panelRight, UserAccount userAccount, Organization organization, Enterprise enterprise) {
        this.panelRight = panelRight;
        this.userAccount = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        initComponents();
        populateTable();
          
    }
public void populateTable () {
   //File DataFile = new File("child.txt");
   //String path = DataFile.getAbsolutePath();
   //System.out.println(path);

   ArrayList<String[]> Rs2 = new ArrayList();
   String[] OneRow;

 //  try{
  //   System.out.println("Attempting to read from file in: "+DataFile.getCanonicalPath());
  /*    BufferedReader brd = new BufferedReader(
                       new FileReader("C:\\Users\\deeps\\OneDrive\\Desktop\\child.txt"));

               while (brd.readLine() != null) {
                   String st = brd.readLine();
                   OneRow = st.split(",");
                   Rs2.add(OneRow);
      DefaultTableModel dtm=(DefaultTableModel) jTable1.getModel();
      dtm.addRow(OneRow);

   }
   }*/
     /*  try{
       BufferedReader br = new BufferedReader(new FileReader("C:\\Users\\deeps\\OneDrive\\Desktop\\child.txt"));
           // get the first line
           // get the columns name from the first line
           // set columns name to the jtable model
           String firstLine = br.readLine().trim();
           String[] columnsName = firstLine.split(",");
           DefaultTableModel model = (DefaultTableModel)childrenTable.getModel();
           model.setColumnIdentifiers(columnsName);

           // get lines from txt file
           //Object[] tableLines = br.readLine();

           // extratct data from lines
           // set data to jtable model
           for(int i = 0; i < tableLines.length; i++)
           {
               String line = tableLines[i].toString().trim();
               String[] dataRow = line.split(",");
               model.addRow(dataRow);
           }
       }
   catch(Exception e){
    String errmsg = e.getMessage();
    System.out.println("File not found:" + errmsg);
   }
   } */
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(250, 150, 146));

        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton1.setText("Apply For Adoption");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jButton1)
                .addContainerGap(294, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FosterParent fosterParent = (FosterParent)userAccount.getEmployee();
        fosterParent.setAdopt(true);
        JOptionPane.showMessageDialog(null, "Your Application has been submitted.");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
