/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.UserRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.CaretakerOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkQueue;
import Business.WorkQueue.AcceptDonationRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author bhash
 */
public class Donation extends javax.swing.JPanel {

    /**
     * Creates new form Donation
     */
    private JPanel panelRight;
      private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    

    public Donation(JPanel panelRight, UserAccount userAccount, Organization organization, Enterprise enterprise) {
        initComponents();
        this.panelRight = panelRight;
        this.userAccount = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;
       
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        Donate = new javax.swing.JButton();
        donorName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dollar25 = new javax.swing.JToggleButton();
        dollar100 = new javax.swing.JToggleButton();
        dollar50 = new javax.swing.JToggleButton();
        dollar500 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cardNum = new javax.swing.JTextField();
        cvvNum = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        expirationDate = new javax.swing.JTextField();

        setBackground(new java.awt.Color(250, 150, 146));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setText("Please Select Gift Amount:");

        Donate.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Donate.setText("Donate");
        Donate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DonateActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setText("Name Of Donor");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/images/Charitable-Donation.jpg"))); // NOI18N

        buttonGroup2.add(dollar25);
        dollar25.setText("$25");
        dollar25.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dollar25ItemStateChanged(evt);
            }
        });

        buttonGroup2.add(dollar100);
        dollar100.setText("$100");
        dollar100.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dollar100ItemStateChanged(evt);
            }
        });

        buttonGroup2.add(dollar50);
        dollar50.setText("$50");
        dollar50.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dollar50ItemStateChanged(evt);
            }
        });

        buttonGroup2.add(dollar500);
        dollar500.setText("$500");
        dollar500.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dollar500ItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setText("Credit Card Information:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel5.setText("Card Number:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel6.setText("CVV Number:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel7.setText("Expiration Date:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(donorName, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dollar25, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dollar50, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dollar100, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dollar500, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cardNum)
                                    .addComponent(cvvNum, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                    .addComponent(expirationDate))))))
                .addContainerGap(223, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Donate)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(donorName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dollar100, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dollar50, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dollar500, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dollar25, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cardNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cvvNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(expirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Donate)
                .addGap(56, 56, 56))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DonateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DonateActionPerformed
        // TODO add your handling code here:
           AcceptDonationRequest request = new AcceptDonationRequest();
        request.setMessage("Donation Initiated");
        request.setSender(null);
        request.setStatus("Acceptance Requested");
        if(dollar25.isSelected()){
        dollar50.setBackground(Color.GRAY);
        dollar100.setBackground(Color.GRAY);
        dollar500.setBackground(Color.GRAY);
        request.setDonatedAmt(25);
        }
        else if(dollar50.isSelected()){
        dollar25.setBackground(Color.GRAY);
        dollar100.setBackground(Color.GRAY);
        dollar500.setBackground(Color.GRAY);
        request.setDonatedAmt(50);
        }
        else if(dollar100.isSelected())
        {
        dollar25.setBackground(Color.GRAY);
        dollar100.setBackground(Color.GRAY);
        dollar500.setBackground(Color.GRAY);
         request.setDonatedAmt(50);
        }
        else if(dollar500.isSelected()){
        dollar25.setBackground(Color.GRAY);
        dollar100.setBackground(Color.GRAY);
        dollar50.setBackground(Color.GRAY);
        request.setDonatedAmt(500);
        }
        else{
            JOptionPane.showMessageDialog(this, ui, "Enter Amount", WIDTH);
        }
        
         Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof CaretakerOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
           
        }
        
       // Organization orgatn = new CaretakerOrganization();
        //orgatn.getWorkQueue().getWorkRequestList().add(request);
       /*  CardLayout layout = (CardLayout)panelRight.getLayout();
        panelRight.add(new PaymentPage(panelRight,system));
        layout.next(panelRight);
         */ 
    
               
    }//GEN-LAST:event_DonateActionPerformed

    private void dollar25ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dollar25ItemStateChanged
        // TODO add your handling code here:
        if(dollar25.isSelected())
        {
            dollar25.setBackground(Color.darkGray);
        }
        else
        {
            dollar25.setBackground(Color.GRAY);
        }
    }//GEN-LAST:event_dollar25ItemStateChanged

    private void dollar50ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dollar50ItemStateChanged
         // TODO add your handling code here:
        if(dollar50.isSelected())
        {
            dollar50.setBackground(Color.darkGray);
        }
        else
        {
            dollar50.setBackground(Color.GRAY);
        }
    }//GEN-LAST:event_dollar50ItemStateChanged

    private void dollar100ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dollar100ItemStateChanged
        // TODO add your handling code here:
        if(dollar100.isSelected())
        {
            dollar100.setBackground(Color.darkGray);
        }
        else
        {
            dollar100.setBackground(Color.GRAY);
        }
    }//GEN-LAST:event_dollar100ItemStateChanged

    private void dollar500ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dollar500ItemStateChanged
        // TODO add your handling code here:
        if(dollar500.isSelected())
        {
            dollar500.setBackground(Color.darkGray);
        }
        else
        {
            dollar500.setBackground(Color.GRAY);
        }
    }//GEN-LAST:event_dollar500ItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Donate;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField cardNum;
    private javax.swing.JTextField cvvNum;
    private javax.swing.JToggleButton dollar100;
    private javax.swing.JToggleButton dollar25;
    private javax.swing.JToggleButton dollar50;
    private javax.swing.JToggleButton dollar500;
    private javax.swing.JTextField donorName;
    private javax.swing.JTextField expirationDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
