/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.UserRole;

import Business.Enterprise.Enterprise;
import Business.Organization.AdminOrganization;
import Business.Organization.CaretakerOrganization;
import Business.Organization.FosterParents;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.UserVerificationWorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author bhash
 */
public class RequestVerificationJpanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestVerificationJpanel
     */
    private JPanel panelRight;
    private String activationCode;
    private String userName;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private String emailID;
    public RequestVerificationJpanel(JPanel panelRight,String activationCode,String userName,UserAccount userAccount,Enterprise enterprise,  String emailID ) {
        initComponents();
        this.panelRight = panelRight;
        this.activationCode = activationCode;
        this.userName = userName;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.emailID = emailID;
     
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        activationCodeTextField = new javax.swing.JTextField();
        requestVerificationButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(250, 150, 146));

        activationCodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activationCodeTextFieldActionPerformed(evt);
            }
        });

        requestVerificationButton.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        requestVerificationButton.setText("Request Verification from Admin");
        requestVerificationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestVerificationButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("Enter Activation Code");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32)
                        .addComponent(activationCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(requestVerificationButton)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(activationCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(requestVerificationButton)
                .addContainerGap(119, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void activationCodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activationCodeTextFieldActionPerformed
        // TODO add your handling code here:
      
    
    }//GEN-LAST:event_activationCodeTextFieldActionPerformed

    private void requestVerificationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestVerificationButtonActionPerformed
        // TODO add your handling code here:
        
          if(activationCode.equals(activationCodeTextField.getText()))
        {
             UserVerificationWorkRequest request = new UserVerificationWorkRequest();
        request.setMessage("Requested User Verification");
        request.setSender(userAccount);
        request.setStatus("Verification Requested");
        request.setEmailID(emailID);
     //   request.setSender(userAccount);
        
      Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof AdminOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
           
        }
                panelRight.removeAll();
        JPanel blankJP = new JPanel();
        blankJP.setBackground(Color.getColor("FA9692"));
        panelRight.add("blank", blankJP);
        CardLayout crdLyt = (CardLayout) panelRight.getLayout();
        crdLyt.next(panelRight);
        }
          else{
              JOptionPane.showMessageDialog(null,"Please Enter Proper Validation Code ");
                      } 

       // dB4OUtil.storeSystem(system);   
    
    
    }//GEN-LAST:event_requestVerificationButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField activationCodeTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton requestVerificationButton;
    // End of variables declaration//GEN-END:variables
}
