/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.UserRole;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Employee.FosterParent;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.FosterParents;
import Business.Organization.Organization;
import Business.Role.FosterParentsRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.Random;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JPanel;
import javax.swing.JOptionPane;
import org.apache.commons.codec.binary.Base64;





/**
 *
 * @author bhash
 */
public class SignupForm extends javax.swing.JPanel {

    /**
     * Creates new form SignupForm
     */
    private JPanel panelRight;
    private String emailID;
    private static final String usernameRegex = "[a-zA-Z0-9]";
   private static final String passwordRegex = "^[\\w+$]+$";
   private static final String emailRegex = "^\\w+@[a-zA-Z_]+[.][a-zA-Z]{2,3}$";
   private static final String numberRegex = "^[0-9]{1,10}$";
   Pattern userNamePattern = Pattern.compile(usernameRegex);
   Pattern passwordPattern = Pattern.compile(passwordRegex);
   Pattern emailPattern = Pattern.compile(emailRegex);
   Pattern numberPattern = Pattern.compile(numberRegex);
   Matcher matchForUserName;
   Matcher matchForPassword;
   Matcher matchForEmail;
   Matcher matchForNumber;
    private EcoSystem system;
    public SignupForm(JPanel panelRight, EcoSystem system) {
        initComponents();
               
        this.panelRight = panelRight;
       
        this.system = system;
        for(Network ntwrk: system.getNetworkList())
          locationListSignup.addItem(ntwrk);
    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userSignupName = new javax.swing.JTextField();
        emailUserSignup = new javax.swing.JTextField();
        numberUserSignUp = new javax.swing.JTextField();
        signUpButton = new javax.swing.JButton();
        backToWelcomePage = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        locationListSignup = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        passwordFieldSignup = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        enterpriseTypeSignup = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(250, 150, 146));

        jLabel1.setText("Name");

        jLabel2.setText("E-mail");

        jLabel3.setText("Phone Number");

        userSignupName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userSignupNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userSignupNameFocusLost(evt);
            }
        });

        emailUserSignup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailUserSignupFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailUserSignupFocusLost(evt);
            }
        });

        numberUserSignUp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                numberUserSignUpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                numberUserSignUpFocusLost(evt);
            }
        });

        signUpButton.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        signUpButton.setText("Next>>");
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });

        backToWelcomePage.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        backToWelcomePage.setText("<<Back");
        backToWelcomePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToWelcomePageActionPerformed(evt);
            }
        });

        jLabel7.setText("Select Netwok(location)");

        locationListSignup.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Please select a Location" }));
        locationListSignup.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                locationListSignupItemStateChanged(evt);
            }
        });
        locationListSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationListSignupActionPerformed(evt);
            }
        });
        locationListSignup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                locationListSignupFocusGained(evt);
            }
        });

        jLabel8.setText("Password");

        passwordFieldSignup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFieldSignupFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFieldSignupFocusLost(evt);
            }
        });

        jLabel9.setText("Select Enterprise type");

        enterpriseTypeSignup.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Enterprise Type" }));
        enterpriseTypeSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseTypeSignupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backToWelcomePage))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userSignupName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(emailUserSignup)
                            .addComponent(numberUserSignUp)
                            .addComponent(locationListSignup, 0, 261, Short.MAX_VALUE)
                            .addComponent(passwordFieldSignup)
                            .addComponent(enterpriseTypeSignup, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(110, 110, 110))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(signUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(backToWelcomePage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(userSignupName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(jLabel8))
                    .addComponent(passwordFieldSignup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailUserSignup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberUserSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(locationListSignup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addComponent(signUpButton)
                        .addGap(73, 73, 73))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enterpriseTypeSignup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backToWelcomePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToWelcomePageActionPerformed
        // TODO add your handling code here:
            CardLayout layout = (CardLayout)panelRight.getLayout();
        panelRight.remove(this);
        layout.previous(panelRight);
    }//GEN-LAST:event_backToWelcomePageActionPerformed

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtonActionPerformed
        // TODO add your handling code here:
        String activationCode = "";
        if(userSignupName.getText().equals("") || emailUserSignup.getText().equals("") || numberUserSignUp.getText().equals(""))       
        {
            JOptionPane.showMessageDialog(null, "Please enter all details");
        }
        else
        {
 
        String numbers = "0123456789"; 
        // Using random method 
        Random rndm_method = new Random(); 
        emailID = emailUserSignup.getText();
        char[] otp = new char[6]; 
  
        for (int i = 0; i < 6; i++) 
        { 
            // Use of charAt() method : to get character value 
            // Use of nextInt() as it is scanning the value as int 
            otp[i] =  numbers.charAt(rndm_method.nextInt(numbers.length())); 
        } 
        String otpText = String.valueOf(otp);
       sendSMS(otpText);
       activationCode = otpText;
      
        }
        Enterprise et =  (Enterprise)enterpriseTypeSignup.getSelectedItem();
        Organization fosterParentOrganization = null;
        
        for(Organization org:et.getOrganizationDirectory().getOrganizationList())
        {
            if(org instanceof FosterParents)
            {
                fosterParentOrganization = org;
            }
        }
        Employee userEmployee = new FosterParent();
        userEmployee.setName(userSignupName.getText());
        
        fosterParentOrganization.getEmployeeDirectory().addEmployee(userEmployee);
        UserAccount userAcct = fosterParentOrganization.getUserAccountDirectory().createUserAccount(userSignupName.getText(), new String(passwordFieldSignup.getPassword()), userEmployee, new FosterParentsRole());
        CardLayout layout = (CardLayout)panelRight.getLayout();
        
        panelRight.add(new RequestVerificationJpanel(panelRight,activationCode,userSignupName.getText(),userAcct,et,emailID));
        layout.next(panelRight);   
    }//GEN-LAST:event_signUpButtonActionPerformed

    private void locationListSignupItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_locationListSignupItemStateChanged
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_locationListSignupItemStateChanged

    private void locationListSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationListSignupActionPerformed
        // TODO add your handling code here:
        for(Network ntwrk: system.getNetworkList()) 
       // Network net=null;
        {
          for(Enterprise entpse: ntwrk.getEnterpriseDirectory().getEnterpriseList())
          {
       
            enterpriseTypeSignup.addItem(entpse);
        }
      
        }           
          
       
          
    }//GEN-LAST:event_locationListSignupActionPerformed

    private void locationListSignupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_locationListSignupFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_locationListSignupFocusGained

    private void enterpriseTypeSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseTypeSignupActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_enterpriseTypeSignupActionPerformed

    private void userSignupNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userSignupNameFocusGained
     
    }//GEN-LAST:event_userSignupNameFocusGained

    private void userSignupNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userSignupNameFocusLost
        // TODO add your handling code here:
     
    }//GEN-LAST:event_userSignupNameFocusLost

    private void passwordFieldSignupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldSignupFocusGained
        // TODO add your handling code here:
        passwordFieldSignup.setText("");
        passwordFieldSignup.setForeground(Color.black);
    }//GEN-LAST:event_passwordFieldSignupFocusGained

    private void passwordFieldSignupFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldSignupFocusLost
        // TODO add your handling code here:
       matchForPassword = passwordPattern.matcher(new String(passwordFieldSignup.getPassword()));
       if(!matchForPassword.matches())
       {
           passwordFieldSignup.setText("Please enter valid password");
           passwordFieldSignup.setForeground(Color.red);
       }
     
      
    }//GEN-LAST:event_passwordFieldSignupFocusLost

    private void emailUserSignupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailUserSignupFocusGained
        // TODO add your handling code here:
        emailUserSignup.setText("");
        emailUserSignup.setForeground(Color.black);
    }//GEN-LAST:event_emailUserSignupFocusGained

    private void emailUserSignupFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailUserSignupFocusLost
        // TODO add your handling code here:
        matchForEmail = emailPattern.matcher(emailUserSignup.getText());
       if(!matchForEmail.matches())
       {
           emailUserSignup.setText("Please enter valid Email");
           emailUserSignup.setForeground(Color.red);
       }
    
    }//GEN-LAST:event_emailUserSignupFocusLost

    private void numberUserSignUpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numberUserSignUpFocusGained
        // TODO add your handling code here:
        numberUserSignUp.setText("");
        numberUserSignUp.setForeground(Color.black);
    }//GEN-LAST:event_numberUserSignUpFocusGained

    private void numberUserSignUpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numberUserSignUpFocusLost
        // TODO add your handling code here:
        matchForNumber = numberPattern.matcher(numberUserSignUp.getText());
       if(!matchForNumber.matches())
       {
           numberUserSignUp.setText("Please enter valid number");
           numberUserSignUp.setForeground(Color.red);
       }
      
    }//GEN-LAST:event_numberUserSignUpFocusLost
void sendSMS(String code)
{
   
         try {
            String phoneNumber = "+13136525820";
            String key = "8679266f-6b30-4ca9-bb27-2e3524eb9bfb";
            String secret = "+ukETh7esUa1VWBJyGnH4w==";
            String message = code +"your verification code";
           
            URL url = new URL("https://messagingapi.sinch.com/v1/sms/" + phoneNumber);
            HttpURLConnection connection = (HttpURLConnection) url.openConnection();
            connection.setDoOutput(true);
            connection.setRequestMethod("POST");
            connection.setRequestProperty("Content-Type", "application/json");
            String userCredentials = "application\\" + key + ":" + secret;
            byte[] encoded = Base64.encodeBase64(userCredentials.getBytes());
            String basicAuth = "Basic " + new String(encoded);
            connection.setRequestProperty("Authorization", basicAuth);
            String postData = "{\"Message\":\"" + message + "\"}";
            OutputStream os = connection.getOutputStream();
            os.write(postData.getBytes());
            StringBuilder response = new StringBuilder();
            BufferedReader br = new BufferedReader(new InputStreamReader(connection.getInputStream()));
            String line;
            while ( (line = br.readLine()) != null)
                response.append(line);
            br.close();
            os.close();
            System.out.println(response.toString());
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
	


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToWelcomePage;
    private javax.swing.JTextField emailUserSignup;
    private javax.swing.JComboBox enterpriseTypeSignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox locationListSignup;
    private javax.swing.JTextField numberUserSignUp;
    private javax.swing.JPasswordField passwordFieldSignup;
    private javax.swing.JButton signUpButton;
    private javax.swing.JTextField userSignupName;
    // End of variables declaration//GEN-END:variables
}
