/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministrativeRole;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Employee.OrphanageEmployee;
import Business.Enterprise.Enterprise;
import Business.Organization.CaretakerOrganization;
import Business.Organization.FosterParents;
import Business.Organization.Organization;
import Business.Role.CaretakerRole;
import Business.Role.SystemAdminRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

/**
 *
 * @author bhash
 */
public class AddEmployee extends javax.swing.JPanel {

    /**
     * Creates new form AddEmployee
     */
      
   private static final String passwordRegex = "^[\\w+$]+$";
   private static final String emailRegex = "^\\w+@[a-zA-Z_]+[.][a-zA-Z]{2,3}$";
 
 
   Pattern passwordPattern = Pattern.compile(passwordRegex);
   Pattern emailPattern = Pattern.compile(emailRegex);
   
   
   Matcher matchForPassword;
   Matcher matchForEmail;
   
    private JPanel panelRight;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem system;
    public AddEmployee(JPanel panelRight,UserAccount userAccount,Organization organization,Enterprise enterprise, EcoSystem system) {
     
        this.panelRight=panelRight;
        this.userAccount = userAccount;
        this.organization= organization;
        this.enterprise = enterprise;
        this.system = system;
           initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        employeeNameTextField = new javax.swing.JTextField();
        employeeEmailTextField = new javax.swing.JTextField();
        createEmployeeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        backToEmployeeManagement = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        employeeDob = new javax.swing.JTextField();
        labelForCaretakerOrganization = new javax.swing.JLabel();
        employeePasswordField = new javax.swing.JPasswordField();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setBackground(new java.awt.Color(250, 150, 146));

        employeeNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                employeeNameTextFieldFocusGained(evt);
            }
        });

        employeeEmailTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                employeeEmailTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                employeeEmailTextFieldFocusLost(evt);
            }
        });

        createEmployeeButton.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        createEmployeeButton.setText("Create & AssignChildren");
        createEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEmployeeButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setText("Name");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setText("Password");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setText("Email");

        backToEmployeeManagement.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        backToEmployeeManagement.setText("Back");
        backToEmployeeManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToEmployeeManagementActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel5.setText("DOB");

        employeeDob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeDobActionPerformed(evt);
            }
        });

        labelForCaretakerOrganization.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        labelForCaretakerOrganization.setText("Caretaker Organization");

        employeePasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeePasswordFieldActionPerformed(evt);
            }
        });
        employeePasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                employeePasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                employeePasswordFieldFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(createEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelForCaretakerOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(backToEmployeeManagement))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                                .addComponent(employeeNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(employeeEmailTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                    .addComponent(employeeDob, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                    .addComponent(employeePasswordField))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backToEmployeeManagement)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(labelForCaretakerOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(employeeNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(employeePasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(32, 32, 32)
                .addComponent(createEmployeeButton)
                .addContainerGap(268, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backToEmployeeManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToEmployeeManagementActionPerformed
 panelRight.remove(this);
                CardLayout cd = (CardLayout)panelRight.getLayout();
                cd.previous(panelRight);      
    }//GEN-LAST:event_backToEmployeeManagementActionPerformed

    private void createEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEmployeeButtonActionPerformed
        // TODO add your handling code here:
         Organization employeeOrganization = null;
        
         
        for(Organization org:enterprise.getOrganizationDirectory().getOrganizationList())
        {
            if(org instanceof CaretakerOrganization)
            {
                employeeOrganization = org;
            }
        }
               Employee employee = new OrphanageEmployee();
                employee.setName(employeeNameTextField.getText());
                employeeOrganization.getEmployeeDirectory().addEmployee(employee);
        
                UserAccount ua = employeeOrganization.getUserAccountDirectory().createUserAccount(employeeNameTextField.getText(), new String(employeePasswordField.getPassword()), employee, new CaretakerRole());
        
     
             JOptionPane.showMessageDialog(null, "Employee Created"); 
                      CardLayout layout = (CardLayout)panelRight.getLayout();
        panelRight.add(new AddChild(panelRight,userAccount,organization,enterprise));
        layout.next(panelRight);   
      

         
         
         
         
    }//GEN-LAST:event_createEmployeeButtonActionPerformed

    private void employeeDobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeDobActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_employeeDobActionPerformed

    private void employeePasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePasswordFieldActionPerformed

    private void employeeNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_employeeNameTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeNameTextFieldFocusGained

    private void employeePasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_employeePasswordFieldFocusGained
        // TODO add your handling code here:
        employeePasswordField.setText("");
        employeePasswordField.setForeground(Color.black);
    }//GEN-LAST:event_employeePasswordFieldFocusGained

    private void employeePasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_employeePasswordFieldFocusLost
        // TODO add your handling code here:
          matchForPassword = passwordPattern.matcher(new String(employeePasswordField.getPassword()));
       if(!matchForPassword.matches())
       {
           employeePasswordField.setText("Please enter valid Email");
           employeePasswordField.setForeground(Color.red);
       }
     
    }//GEN-LAST:event_employeePasswordFieldFocusLost

    private void employeeEmailTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_employeeEmailTextFieldFocusGained
        // TODO add your handling code here:
        employeeEmailTextField.setText("");
        employeeEmailTextField.setForeground(Color.black);
    }//GEN-LAST:event_employeeEmailTextFieldFocusGained

    private void employeeEmailTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_employeeEmailTextFieldFocusLost
        // TODO add your handling code here:
       matchForEmail = emailPattern.matcher(employeeEmailTextField.getText());
       if(!matchForEmail.matches())
       {
           employeeEmailTextField.setText("Please enter valid Email");
           employeeEmailTextField.setForeground(Color.red);
       }
    }//GEN-LAST:event_employeeEmailTextFieldFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToEmployeeManagement;
    private javax.swing.JButton createEmployeeButton;
    private javax.swing.JTextField employeeDob;
    private javax.swing.JTextField employeeEmailTextField;
    private javax.swing.JTextField employeeNameTextField;
    private javax.swing.JPasswordField employeePasswordField;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelForCaretakerOrganization;
    // End of variables declaration//GEN-END:variables
}
