/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministrativeRole;

import Business.Enterprise.Enterprise;
import Business.Organization.AdminOrganization;
import Business.Organization.Organization;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Business.WorkQueue.RequestResources;
import Business.WorkQueue.UserVerificationWorkRequest;
import javax.swing.JOptionPane;

/**
 *
 * @author barma
 */
public class RequestedResourcesFromEmployees extends javax.swing.JPanel {

    /**
     * Creates new form RequestedResourcesFromEmployees
     */
    private JPanel panelRight;
   private UserAccount userAccount;
   private Organization organization;
   private Enterprise enterprise;
   public RequestedResourcesFromEmployees(JPanel panelRight, UserAccount userAccount, Organization organization, Enterprise enterprise) {

       this.panelRight = panelRight;
       this.userAccount = userAccount;
       this.organization = organization;
       this.enterprise = enterprise;
       initComponents();
       populateTable();

   }
   
   void populateTable()
{
   DefaultTableModel model = (DefaultTableModel) RequestToAdmin.getModel();

       model.setRowCount(0);
       for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList())
       {

           if(org.getName().equals("Caretaker Organization"))
       {
       
       for (WorkRequest request : org.getWorkQueue().getWorkRequestList()){
            if(request instanceof RequestResources)
            {
           
           Object[] row = new Object[4];
           row[0] = request;
          
          
           String result = ((RequestResources)request).getRequestResourcesResult();
           row[1] = result == null ? "Waiting" : result;
            row[2] = request.getSender().getEmployee().getName()+"From CareTaker";

           model.addRow(row);
       }
       }

       }
       }
       }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        RequestToAdmin = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(250, 150, 146));

        RequestToAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Status", "Waiting/Verified", "Sender"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(RequestToAdmin);

        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton2.setText("Accept");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(666, 666, 666)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jButton2)
                .addContainerGap(188, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRow =RequestToAdmin.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select row");
        }
        else
        {
            RequestResources acceptRequest = (RequestResources) RequestToAdmin.getValueAt(selectedRow, 0);

            acceptRequest.setRequestResourcesResult("Accepted");

            acceptRequest.setStatus("Acknowledged");
            RequestResources request = new RequestResources();
            request.setMessage("Resource needed");
            request.getSender();
            populateTable();
    }//GEN-LAST:event_jButton2ActionPerformed
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable RequestToAdmin;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
