/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministrativeRole;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Employee.OrphanageEmployee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.AdminOrganization;
import Business.Organization.CaretakerOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ChangeEnterpriseRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author bhash
 */
public class TransferEmployee extends javax.swing.JPanel {

    /**
     * Creates new form TransferEmployee
     */  
    Employee employee;
    Organization org;
    EcoSystem sys;
    Enterprise enterprise;
    private UserAccount userAccount;
     
    /**
     * Creates new form EmployeeInformation
     */
    private JPanel panelRight;
    
    public TransferEmployee(JPanel userProcessContainer,Employee employee, Organization org , EcoSystem system, Enterprise enterprise,UserAccount userAccount) {
        initComponents();
         panelRight=userProcessContainer;
        this.employee = employee;
        this.org = org;
        this.sys = system;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        
        for(Network net: system.getNetworkList())
        {
            for(Enterprise e: net.getEnterpriseDirectory().getEnterpriseList())
            {
                if(e.equals(enterprise))
                {
                continue;}
                else{
                 transferToEnterprise.addItem(e);
                }
            }
        }
        currentEnterpriseLabel.setText(employee.getName());
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        transferToEnterprise = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        currentEnterpriseLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(250, 150, 146));

        transferToEnterprise.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select an enterprise to transfer" }));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setText("Current Employee");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setText("Transfer To Enterprise");

        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton1.setText("Transfer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("<<Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(transferToEnterprise, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(currentEnterpriseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(currentEnterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(transferToEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addComponent(jButton1)
                .addContainerGap(233, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Enterprise e = (Enterprise)transferToEnterprise.getSelectedItem();
          // Organization org = null;
            ChangeEnterpriseRequest request = new ChangeEnterpriseRequest();
             request.setMessage("Employee Transfer");
            for(Network net: sys.getNetworkList())
        {
            for(Enterprise ent: net.getEnterpriseDirectory().getEnterpriseList())
            {
                for(Organization org: ent.getOrganizationDirectory().getOrganizationList())
                {
                 if(org instanceof CaretakerOrganization)
                for(UserAccount ua: org.getUserAccountDirectory().getUserAccountList())
                {
                    if(ua.getEmployee().getName().equals(employee.getName()))
                    {
                        request.setSender(ua); 
                    }
                }
             }
            }
        }
            request.setStatus("Employee Transfer Requested");
            request.setOrphanEmployee((OrphanageEmployee) employee);
             e.getWorkQueue().getWorkRequestList().add(request);
          //  userAccount.getWorkQueue().getWorkRequestList().add(request);
           
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 panelRight.remove(this);
                CardLayout cd = (CardLayout)panelRight.getLayout();
                cd.previous(panelRight);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currentEnterpriseLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox transferToEnterprise;
    // End of variables declaration//GEN-END:variables
}
