/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.EmployeeRole;

import Business.Child.Child;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Employee.FosterParent;
import Business.Employee.OrphanageEmployee;
import Business.Enterprise.Enterprise;
import Business.Organization.FosterParents;
import Business.Organization.OrganizationDirectory;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bhash
 */
public class ManageChild extends javax.swing.JPanel {

    /**
     * Creates new form ChildrenDetails
     */
   private JPanel panelRight;
   private Enterprise enterprise;
   private UserAccount userAccount;
   private Organization organization;
   private EcoSystem system;
   public ManageChild(JPanel panelRight, UserAccount userAccount, Organization organization,Enterprise enterprise,EcoSystem system) {

       this.panelRight = panelRight;
       this.enterprise = enterprise;
       this.userAccount = userAccount;
       this.organization = organization;
       this.system=system;
        initComponents();
       populateTable();
      
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        childTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(250, 150, 146));

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Email"
            }
        ));
        jScrollPane1.setViewportView(userTable);

        jButton3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton3.setText("Assign");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setText("Users");

        childTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Gender", "DOB"
            }
        ));
        jScrollPane2.setViewportView(childTable);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel2.setText("Child");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton3)
                            .addGap(185, 185, 185))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jButton3)
                .addGap(158, 158, 158))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void populateTable(){
     DefaultTableModel model = (DefaultTableModel) userTable.getModel(); 
     model.setRowCount(0);
     
     DefaultTableModel model1 = (DefaultTableModel) childTable.getModel();
     model1.setRowCount(0);

      for(Organization org:enterprise.getOrganizationDirectory().getOrganizationList())
      {
                if(org instanceof FosterParents)
                {
        for(UserAccount uacc:org.getUserAccountDirectory().getUserAccountList())
        {
          FosterParent parent = (FosterParent)uacc.getEmployee();
          if(parent.getFosterChild()==null && parent.isAdopt())
          {
                Object[] row = new Object[1];
                row[0] = parent;
              //  row[1]=uacc.getEmail();
               model.addRow(row);
          }
        }
      }
      }
      for(Employee emp: organization.getEmployeeDirectory().getEmployeeList())
      {
          OrphanageEmployee employee = (OrphanageEmployee)emp;
          for(Child child : employee.getChildrenList().getChildList())
          {
              if(child.getFosterParent()==null)
              {
                Object[] row1 = new Object[2];
                row1[0] = child;
                row1[1]=child.getGender();
               model1.addRow(row1);
              }
          }
      }
}
 
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int selectedRowforUser =userTable.getSelectedRow();
        int selectedRowforChild =childTable.getSelectedRow();
        if ((selectedRowforUser < 0)||(selectedRowforChild<0)){
            JOptionPane.showMessageDialog(null, "Please select row");
      }
        else
        {

        FosterParent fosterParent = (FosterParent) userTable.getValueAt(selectedRowforUser, 0);
        Child childSel=(Child) childTable.getValueAt(selectedRowforChild, 0);
        fosterParent.assignFosterChild(childSel);
           JOptionPane.showMessageDialog(null,"Child has been assigned");
           populateTable();
        }        
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable childTable;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables
}
