/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.EmployeeRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import Business.WorkQueue.AcceptDonationRequest;
import Business.WorkQueue.RequestResources;
import com.itextpdf.awt.DefaultFontMapper;
import com.itextpdf.text.Document;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfTemplate;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.BorderLayout;
import java.awt.Graphics2D;
import java.awt.GridLayout;
import java.awt.geom.Rectangle2D;
import java.io.FileOutputStream;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.plot.PiePlot3D;
import Business.Organization.AdminOrganization;

/**
 *
 * @author bhash
 */
public class ManageResources extends javax.swing.JPanel {

    /**
     * Creates new form ManageResources
     */
   private JPanel panelRight;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Organization organization;
    private EcoSystem system;
    private Integer amountDon;
    Integer foodAmt ;
    Integer medAmt;
    Integer eduAmt;
    public ManageResources(JPanel panelRight, UserAccount userAccount, Organization organization,Enterprise enterprise,EcoSystem system) {
       
        this.panelRight = panelRight;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.organization = organization;
        this.system = system;
         initComponents();
         populateTable();
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void calculate(){
    foodAmt = Integer.parseInt(foodCal.getText());
    medAmt = Integer.parseInt(medCal.getText());
    eduAmt = Integer.parseInt(eduCal.getText());
     if(foodAmt<medAmt && foodAmt<eduAmt )
     {
         foodAmt = foodAmt+amountDon;
         foodCal.setText(foodAmt.toString());
     }
    else if(medAmt<foodAmt && medAmt<eduAmt )
     {
         medAmt = medAmt+amountDon;
         medCal.setText(medAmt.toString());
         
     }
    else if(eduAmt<foodAmt && eduAmt<medAmt )
     {
         eduAmt = eduAmt+amountDon;
         eduCal.setText(eduAmt.toString());
     }
    else{
       if(foodAmt==medAmt){foodAmt = foodAmt+amountDon;
       foodCal.setText(foodAmt.toString()); 
       
    }
      else if(medAmt==eduAmt)
      {
         medAmt = medAmt+amountDon;
         medCal.setText(medAmt.toString()); 
      }
      else{
         eduAmt = eduAmt+amountDon;
         eduCal.setText(eduAmt.toString());     
      }
    }
    
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        acceptDonationRequestTable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        foodCal = new javax.swing.JLabel();
        eduCal = new javax.swing.JLabel();
        medCal = new javax.swing.JLabel();

        setBackground(new java.awt.Color(250, 150, 146));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("Resource Status");

        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jButton1.setText("Generate Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        acceptDonationRequestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Receiver", "Status", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(acceptDonationRequestTable);

        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jButton2.setText("Accept");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setText("Investment List:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel3.setText("Food:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel4.setText("Medical:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel5.setText("Education:");

        foodCal.setText("0");

        eduCal.setText("0");

        medCal.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButton2)
                                        .addGap(30, 30, 30)
                                        .addComponent(jButton1))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(eduCal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addComponent(foodCal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(32, 32, 32)
                                                .addComponent(medCal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(163, 163, 163))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(foodCal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(medCal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(eduCal))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(72, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
void populateTable()
{
    DefaultTableModel model = (DefaultTableModel) acceptDonationRequestTable.getModel();
        
        model.setRowCount(0);
        for(Organization org: enterprise.getOrganizationDirectory().getOrganizationList())
        {
            if(org.getName().equals("Caretaker Organization"))
            {
        for (WorkRequest request : org.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[4];
            row[0] = request;
            row[1] = request.getReceiver();
       
            String result = ((AcceptDonationRequest) request).getTestResult();
            row[2] = result == null ? "Waiting" : result;
            row[3] = request.getDonatedAmt();
            model.addRow(row);
        }
            }
}
} 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
  
      DefaultPieDataset dataset = new DefaultPieDataset();
      dataset.setValue( "Food" , foodAmt );  
      dataset.setValue( "Medical" , medAmt );   
      dataset.setValue( "Education" , eduAmt);    
     // dataset.setValue( "Nokia Lumia" , new Double( 10 ) );  
    
      
      JFreeChart chart = ChartFactory.createPieChart3D("Current Investment",dataset,true,true,false);
        
      
       final PiePlot3D plot = (PiePlot3D) chart.getPlot();
       plot.setStartAngle(270);
       plot.setForegroundAlpha(0.60f);
       plot.setInteriorGap(0.02);
       
       
        ChartPanel chartPanel = new ChartPanel(chart);
         JDialog dialog = new JDialog();
        dialog.add(chartPanel, BorderLayout.CENTER);
        dialog.setLayout(new GridLayout(1, 1));
        dialog.setSize(700, 500);
        dialog.setVisible(true);
     writeChartToPDF(chart, 500, 400, "C:\\Users\\bhash\\OneDrive\\Documents\\piechart.pdf");
   }
public static void writeChartToPDF(JFreeChart chart, int width, int height, String fileName) {
        PdfWriter writer = null;

        Document document = new Document();

        try {
            writer = PdfWriter.getInstance(document, new FileOutputStream(
                    fileName));
            document.open();
            PdfContentByte contentByte = writer.getDirectContent();
            PdfTemplate template = contentByte.createTemplate(width, height);
            Graphics2D graphics2d = template.createGraphics(width, height,
                    new DefaultFontMapper());
            Rectangle2D rectangle2d = new Rectangle2D.Double(0, 0, width,
                    height);

            chart.draw(graphics2d, rectangle2d);
            
            graphics2d.dispose();
            contentByte.addTemplate(template, 0, 0);

        } catch (Exception e) {
            e.printStackTrace();
        }
        document.close();
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         int selectedRow =acceptDonationRequestTable.getSelectedRow();
          if (selectedRow < 0){
              JOptionPane.showMessageDialog(null, "Please select row");
        }
          else
          {
          
             AcceptDonationRequest acceptRequest = (AcceptDonationRequest) acceptDonationRequestTable.getValueAt(selectedRow, 0);
       
            acceptRequest.setTestResult("Confirmed");
           
        acceptRequest.setStatus("Accepted");
     
        
        populateTable();
        
   amountDon = (Integer)acceptDonationRequestTable.getValueAt(selectedRow, 3);
     calculate(); 
        RequestResources request = new RequestResources();
       request.setMessage("Resource needed");
       request.setSender(userAccount);
       request.setStatus("Awaiting ");

     Organization org = null;
       for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
           if (organization instanceof AdminOrganization){
               org = organization;
               break;
           }
       }
       if (org!=null){
           org.getWorkQueue().getWorkRequestList().add(request);
           userAccount.getWorkQueue().getWorkRequestList().add(request);

       }
          
        
    }//GEN-LAST:event_jButton2ActionPerformed
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable acceptDonationRequestTable;
    private javax.swing.JLabel eduCal;
    private javax.swing.JLabel foodCal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel medCal;
    // End of variables declaration//GEN-END:variables
}
